### ISSUE TITLE
Forma de interactuar en el perfil - menú lateral

### ISSUE THREAD

**Issue by teanocrata** [teanocrata/OpenSmartCountry#92]
- [x] Dar de alta una parcela #153 #154 #155 #156
- [x] Añadir texto, fotos, lista de objetivos privada #157
- [x] Especificar foto de perfil, nivel de privacidad de tu parcela #168
- [x] Descargar informe #160 #161

- Temas técnicos: #166

**Comment by teanocrata** [comment]
La parte de navegación por el perfil de la parcela la dejo para la #90 y sus relacionadas
